# Generated by Django 3.0.7 on 2020-12-11 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('public_read', models.BooleanField(default=True)),
                ('public_write', models.BooleanField(default=True)),
                ('editors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
