# Generated by Django 3.0.7 on 2021-02-11 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210202_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='anonymous_users',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='editors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scene',
            name='public_read',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='public_write',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
