# Generated by Django 3.1.8 on 2021-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210211_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='video_conference',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
