# Generated by Django 3.1.13 on 2021-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scene_video_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
