# Generated by Django 3.1.12 on 2021-09-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scene_video_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='public_listing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
