# Generated by Django 3.2.25 on 2025-01-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250109_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namespace',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='owners',
        ),
    ]
