# Generated by Django 4.2.28 on 2026-02-17 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20250130_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-\\.]+\\/[a-zA-Z0-9_\\-\\.]+$', 'Only alphanumeric, underscore, hyphen, period, in namespace/idname format allowed.')]),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-\\.]*$', 'Only alphanumeric, underscore, hyphen allowed.')]),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-\\.]+\\/[a-zA-Z0-9_\\-\\.]+$', 'Only alphanumeric, underscore, hyphen, period, in namespace/idname format allowed.')]),
        ),
    ]
