"""Tests for users/mqtt.py generate_arena_token().

These tokens are the only thing standing between a client and the MQTT broker:
the 'publ'/'subs' claim arrays are the client's publish/subscribe access control
list. The matrix below crosses caller privilege (anonymous, authenticated owner,
granted editor, granted viewer, staff) with the scene permission flags
(public_read, public_write, anonymous_users, users, video_conference).

Tokens are signed with a throwaway RSA key generated by users/tests/mqtt_keys.py
and verified here, so the claim arrays are read back out of a real signed JWT.
These tests use the database because generate_arena_token() reads Scene and
Namespace permission rows.
"""

import datetime
import os
from unittest import mock

import jwt
from django.contrib.auth.models import AnonymousUser, User
from django.test import TestCase, override_settings

from users.models import Namespace, Scene
from users.mqtt import DEF_JWT_DURATION, generate_arena_token
from users.tests.mqtt_keys import (
    MISSING_KEY_PATH,
    PRIVATE_KEY_PATH,
    PUBLIC_KEY_PEM,
    decode_token,
    make_ids,
    token_header,
)

REALM = "realm"


@override_settings(MQTT_TOKEN_PRIVKEY=PRIVATE_KEY_PATH)
class ArenaTokenTestCase(TestCase):
    """Shared users/scenes for the token matrix."""

    @classmethod
    def setUpTestData(cls):
        cls.anon = AnonymousUser()
        cls.bob = User.objects.create_user(username="bob", password="pw")
        cls.staff = User.objects.create_user(username="root", password="pw", is_staff=True)
        cls.edith = User.objects.create_user(username="edith", password="pw")

        # scene permission rows exercising each flag
        cls.scene_bob = Scene.objects.create(name="bob/scene1")
        cls.scene_no_anon = Scene.objects.create(name="carol/noanon", anonymous_users=False)
        cls.scene_no_read = Scene.objects.create(name="carol/noread", public_read=False)
        cls.scene_pub_write = Scene.objects.create(name="carol/pubwrite", public_write=True)
        cls.scene_no_users = Scene.objects.create(name="carol/nousers", users=False)
        cls.scene_no_video = Scene.objects.create(name="carol/novideo", video_conference=False)

        # grants on someone else's scene / namespace
        cls.scene_edit = Scene.objects.create(name="carol/shared")
        cls.scene_edit.editors.add(cls.edith)
        cls.scene_view = Scene.objects.create(name="carol/viewonly")
        cls.scene_view.viewers.add(cls.edith)
        cls.ns_edit = Namespace.objects.create(name="frank")
        cls.ns_edit.editors.add(cls.edith)
        cls.ns_view = Namespace.objects.create(name="grace")
        cls.ns_view.viewers.add(cls.edith)

    def claims(self, **kwargs):
        token = generate_arena_token(**kwargs)
        self.assertIsNotNone(token, "expected a token, got None")
        return decode_token(token)


class TokenEnvelopeTests(ArenaTokenTestCase):
    """The parts of the token that must hold for every caller."""

    def test_sub_claim_is_username_for_anonymous(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike"),
        )
        self.assertEqual(claims["sub"], "anonymous-mike")

    def test_sub_claim_is_username_for_authenticated_user(self):
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ns_scene="bob/scene1",
            ids=make_ids("bob"),
        )
        self.assertEqual(claims["sub"], "bob")

    def test_exp_claim_always_present(self):
        cases = {
            "anonymous scene": dict(
                user=self.anon, username="anonymous-mike", ns_scene="carol/plain",
                ids=make_ids("anonymous-mike"),
            ),
            "anonymous denied scene": dict(
                user=self.anon, username="anonymous-mike", ns_scene="carol/noanon",
                ids=make_ids("anonymous-mike"),
            ),
            "authenticated scene": dict(
                user=self.bob, username="bob", ns_scene="bob/scene1", ids=make_ids("bob"),
            ),
            "staff scene": dict(
                user=self.staff, username="root", ns_scene="carol/plain", ids=make_ids("root"),
            ),
            "no scene": dict(user=self.bob, username="bob", ids=make_ids("bob")),
            "device": dict(user=self.bob, username="bob", ns_device="bob/dev1"),
        }
        for label, kwargs in cases.items():
            with self.subTest(case=label):
                claims = self.claims(realm=REALM, **kwargs)
                self.assertIn("exp", claims)

    def test_exp_uses_default_duration(self):
        before = datetime.datetime.now(datetime.timezone.utc)
        claims = self.claims(user=self.bob, username="bob", realm=REALM, ids=make_ids("bob"))
        expected = (before + DEF_JWT_DURATION).timestamp()
        self.assertAlmostEqual(claims["exp"], expected, delta=10)

    def test_exp_uses_requested_duration(self):
        before = datetime.datetime.now(datetime.timezone.utc)
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ids=make_ids("bob"),
            duration=datetime.timedelta(days=1),
        )
        expected = (before + datetime.timedelta(days=1)).timestamp()
        self.assertAlmostEqual(claims["exp"], expected, delta=10)

    def test_token_is_signed_rs256_with_configured_key(self):
        token = generate_arena_token(
            user=self.bob, username="bob", realm=REALM, ids=make_ids("bob")
        )
        self.assertEqual(token_header(token)["alg"], "RS256")
        # verifying with the fixture public key must succeed ...
        jwt.decode(token, PUBLIC_KEY_PEM, algorithms=["RS256"], options={"verify_aud": False})
        # ... and the signature must actually be checked
        tampered = token[:-4] + ("aaaa" if not token.endswith("aaaa") else "bbbb")
        with self.assertRaises(jwt.InvalidTokenError):
            jwt.decode(tampered, PUBLIC_KEY_PEM, algorithms=["RS256"], options={"verify_aud": False})

    @override_settings(MQTT_TOKEN_PRIVKEY=MISSING_KEY_PATH)
    def test_missing_private_key_returns_none(self):
        self.assertIsNone(
            generate_arena_token(user=self.bob, username="bob", realm=REALM, ids=make_ids("bob"))
        )

    def test_malformed_ns_scene_returns_none(self):
        for ns_scene in ["noslash", "too/many/parts", ""]:
            with self.subTest(ns_scene=ns_scene):
                token = generate_arena_token(
                    user=self.bob,
                    username="bob",
                    realm=REALM,
                    ns_scene=ns_scene,
                    ids=make_ids("bob"),
                )
                if ns_scene == "":
                    # falsy: treated as "no scene requested", not an error
                    self.assertIsNotNone(token)
                else:
                    self.assertIsNone(token)

    def test_malformed_ns_device_returns_none(self):
        for ns_device in ["noslash", "too/many/parts"]:
            with self.subTest(ns_device=ns_device):
                self.assertIsNone(
                    generate_arena_token(
                        user=self.bob, username="bob", realm=REALM, ns_device=ns_device
                    )
                )

    @override_settings(
        PUBSUB={
            "mqtt_server": {"host": "localhost", "port": 8883},
            "mqtt_realm": "otherrealm",
            "mqtt_username": "arena_account",
        }
    )
    def test_realm_defaults_to_configured_pubsub_realm(self):
        claims = self.claims(
            user=self.bob, username="bob", ns_scene="bob/scene1", ids=make_ids("bob")
        )
        topics = claims.get("publ", []) + claims.get("subs", [])
        for topic in topics:
            with self.subTest(topic=topic):
                self.assertTrue(
                    topic.startswith("otherrealm/") or topic.startswith("$NETWORK"),
                    f"unexpected realm in {topic}",
                )
        self.assertIn("otherrealm/s/bob/+/+/+/+", claims["subs"])

    def test_network_latency_publish_is_always_granted(self):
        for label, kwargs in {
            "anonymous denied scene": dict(
                user=self.anon, username="anonymous-mike", ns_scene="carol/noanon",
                ids=make_ids("anonymous-mike"),
            ),
            "device": dict(user=self.bob, username="bob", ns_device="bob/dev1"),
            "no scene": dict(user=self.bob, username="bob", ids=make_ids("bob")),
        }.items():
            with self.subTest(case=label):
                claims = self.claims(realm=REALM, **kwargs)
                self.assertIn("$NETWORK/latency", claims["publ"])

    def test_network_metrics_subscribe_only_without_scene_or_device(self):
        general = self.claims(user=self.bob, username="bob", realm=REALM, ids=make_ids("bob"))
        self.assertIn("$NETWORK", general["subs"])

        scene = self.claims(
            user=self.bob, username="bob", realm=REALM, ns_scene="bob/scene1", ids=make_ids("bob")
        )
        self.assertNotIn("$NETWORK", scene["subs"])

        device = self.claims(user=self.bob, username="bob", realm=REALM, ns_device="bob/dev1")
        self.assertNotIn("$NETWORK", device["subs"])


class AnonymousScenePermissionTests(ArenaTokenTestCase):
    def test_default_scene_permissions(self):
        """No Scene row: model defaults (public read, no public write, users, video)."""
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike", camid=True, handleftid=True, handrightid=True),
        )
        uid = "anonymous-mike_0000000001"
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/g/carol/p/+",
                f"realm/s/carol/plain/+/{uid}_web/{uid}",
                f"realm/s/carol/plain/+/{uid}_web/{uid}/+",
                f"realm/s/carol/plain/u/{uid}_web/handLeft_{uid}",
                f"realm/s/carol/plain/u/{uid}_web/handLeft_{uid}/+",
                f"realm/s/carol/plain/u/{uid}_web/handRight_{uid}",
                f"realm/s/carol/plain/u/{uid}_web/handRight_{uid}/+",
            ],
        )
        self.assertEqual(
            claims["subs"],
            [
                "realm/g/carol/p/+",
                "realm/s/carol/plain/+/+/+",
                f"realm/s/carol/plain/+/+/+/{uid}/#",
            ],
        )

    def test_anonymous_users_disabled_grants_no_scene_access(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/noanon",
            ids=make_ids("anonymous-mike", camid=True),
        )
        self.assertEqual(claims["publ"], ["$NETWORK/latency"])
        self.assertNotIn("subs", claims)

    def test_public_read_disabled_removes_scene_subscriptions(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/noread",
            ids=make_ids("anonymous-mike"),
        )
        self.assertEqual(claims["subs"], ["realm/g/carol/p/+"])
        for topic in claims["subs"]:
            self.assertNotIn("carol/noread", topic)

    def test_public_write_enabled_adds_scene_object_publish(self):
        uid = "anonymous-mike_0000000001"
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/pubwrite",
            ids=make_ids("anonymous-mike"),
        )
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/g/carol/p/+",
                f"realm/s/carol/pubwrite/+/{uid}_web/{uid}",
                f"realm/s/carol/pubwrite/+/{uid}_web/{uid}/+",
                f"realm/s/carol/pubwrite/o/{uid}_web/#",
                "realm/s/carol/pubwrite/p/+/#",
            ],
        )

    def test_public_write_disabled_has_no_scene_object_publish(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike"),
        )
        for topic in claims["publ"]:
            self.assertNotIn("/o/", topic, f"unexpected object write grant: {topic}")

    def test_users_disabled_removes_presence_publish(self):
        uid = "anonymous-mike_0000000001"
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/nousers",
            ids=make_ids("anonymous-mike", camid=True, handleftid=True),
        )
        # no avatar/presence publish topics remain ...
        for topic in claims["publ"]:
            self.assertNotIn("/u/", topic, f"unexpected user object grant: {topic}")
            self.assertNotIn("handLeft", topic)
        # ... but render-fusion/env/debug and program publishes are unaffected
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/g/carol/p/+",
                f"realm/s/carol/nousers/d/{uid}_web/{uid}/-",
                f"realm/s/carol/nousers/e/{uid}_web/{uid}/-",
                f"realm/s/carol/nousers/p/{uid}_web/{uid}",
                f"realm/s/carol/nousers/r/{uid}_web/{uid}/-",
            ],
        )
        # scene reads still allowed (public_read default)
        self.assertIn("realm/s/carol/nousers/+/+/+", claims["subs"])


class JitsiClaimTests(ArenaTokenTestCase):
    """The a/v (Jitsi) claims are only minted for camera-carrying a/v scenes."""

    @mock.patch.dict(os.environ, {"HOSTNAME": "arena.example.com"})
    def test_av_scene_adds_jitsi_claims_and_kid_header(self):
        token = generate_arena_token(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike", camid=True),
        )
        self.assertEqual(token_header(token)["kid"], "arena.example.com")
        claims = decode_token(token)
        self.assertEqual(claims["aud"], "arena")
        self.assertEqual(claims["iss"], "arena-account")
        self.assertEqual(claims["room"], "carol_plain")

    def test_room_name_is_lowercased_and_sanitized(self):
        """Scene name doubles as the Jitsi room name; RFC 3986 reserved chars -> '_'."""
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="Carol/My+Scene(1)",
            ids=make_ids("anonymous-mike", camid=True),
        )
        self.assertEqual(claims["room"], "carol_my_scene_1_")

    def test_no_jitsi_claims_without_camera(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike"),
        )
        for claim in ("aud", "iss", "room"):
            self.assertNotIn(claim, claims)

    def test_no_jitsi_claims_when_video_conference_disabled(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/novideo",
            ids=make_ids("anonymous-mike", camid=True),
        )
        for claim in ("aud", "iss", "room"):
            self.assertNotIn(claim, claims)

    def test_jitsi_claims_still_minted_when_anonymous_users_disabled(self):
        """Documents current behaviour, which looks like a gap.

        The a/v block only consults the 'users' and 'video_conference' flags, so
        an anonymous caller who is refused every MQTT topic on the scene
        (anonymous_users=False) still receives aud/iss/room for that scene's
        Jitsi room. Pinned here so any change to this is deliberate.
        """
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/noanon",
            ids=make_ids("anonymous-mike", camid=True),
        )
        self.assertEqual(claims["publ"], ["$NETWORK/latency"])
        self.assertEqual(claims["aud"], "arena")
        self.assertEqual(claims["room"], "carol_noanon")

    def test_no_jitsi_claims_when_users_disabled(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/nousers",
            ids=make_ids("anonymous-mike", camid=True),
        )
        for claim in ("aud", "iss", "room"):
            self.assertNotIn(claim, claims)


class AuthenticatedScenePermissionTests(ArenaTokenTestCase):
    def test_owner_gets_namespace_wide_scene_rights(self):
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ns_scene="bob/scene1",
            ids=make_ids("bob"),
        )
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/d/bob/#",
                "realm/g/bob/p/+",
                "realm/s/bob/+/o/bob_0000000001_web/#",
                "realm/s/bob/+/p/+/#",
                "realm/s/bob/scene1/+/bob_0000000001_web/bob_0000000001",
                "realm/s/bob/scene1/+/bob_0000000001_web/bob_0000000001/+",
            ],
        )
        self.assertEqual(
            claims["subs"],
            [
                "realm/d/bob/#",
                "realm/g/bob/p/+",
                "realm/s/bob/+/+/+/+",
                "realm/s/bob/+/+/+/+/bob_0000000001/#",
            ],
        )

    def test_owner_render_fusion_and_environment_host_grants(self):
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ns_scene="bob/scene1",
            ids=make_ids("bob", renderfusionid=True, environmentid=True),
        )
        self.assertIn("realm/s/bob/+/r/bob_0000000001_web/-", claims["publ"])
        self.assertIn("realm/s/bob/+/r/bob_0000000001_web/-/+", claims["publ"])
        self.assertIn("realm/s/bob/+/e/bob_0000000001_web/-", claims["publ"])
        self.assertIn("realm/s/bob/+/e/bob_0000000001_web/-/+", claims["publ"])
        self.assertIn("realm/s/bob/+/r/+/+/-/#", claims["subs"])
        self.assertIn("realm/s/bob/+/e/+/+/-/#", claims["subs"])

    def test_non_owner_without_grant_gets_only_public_scene_rights(self):
        """bob on carol's default scene: read-only there, plus his own namespace."""
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("bob"),
        )
        self.assertIn("realm/s/carol/plain/+/+/+", claims["subs"])
        for topic in claims["publ"]:
            self.assertFalse(
                topic.startswith("realm/s/carol/plain/o/"),
                f"unexpected object write grant on another user's scene: {topic}",
            )

    def test_staff_gets_all_namespaces_and_all_devices(self):
        claims = self.claims(
            user=self.staff,
            username="root",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("root"),
        )
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/d/#",
                "realm/g/carol/p/+",
                "realm/s/+/+/o/root_0000000001_web/#",
                "realm/s/+/+/p/+/#",
                "realm/s/carol/plain/+/root_0000000001_web/root_0000000001",
                "realm/s/carol/plain/+/root_0000000001_web/root_0000000001/+",
            ],
        )
        self.assertEqual(
            claims["subs"],
            [
                "realm/d/#",
                "realm/g/carol/p/+",
                "realm/s/+/+/+/+/+",
                "realm/s/+/+/+/+/+/root_0000000001/#",
            ],
        )
        self.assertNotIn("realm/d/root/#", claims["publ"])

    def test_scene_editor_grant_adds_write_access(self):
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="carol/shared",
            ids=make_ids("edith"),
        )
        self.assertIn("realm/s/carol/shared/o/edith_0000000001_web/#", claims["publ"])
        self.assertIn("realm/s/carol/shared/p/+/#", claims["publ"])
        self.assertIn("realm/s/carol/shared/+/+/+", claims["subs"])
        self.assertIn("realm/s/carol/shared/+/+/+/edith_0000000001/#", claims["subs"])

    def test_scene_viewer_grant_adds_read_access_only(self):
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="carol/viewonly",
            ids=make_ids("edith"),
        )
        self.assertIn("realm/s/carol/viewonly/+/+/+", claims["subs"])
        for topic in claims["publ"]:
            self.assertFalse(
                topic.startswith("realm/s/carol/viewonly/o/"),
                f"viewer must not get object write: {topic}",
            )

    def test_namespace_editor_grant_covers_whole_namespace(self):
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="frank/anyscene",
            ids=make_ids("edith"),
        )
        self.assertIn("realm/s/frank/+/o/edith_0000000001_web/#", claims["publ"])
        self.assertIn("realm/s/frank/+/+/+/+", claims["subs"])

    def test_namespace_viewer_grant_is_read_only(self):
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="grace/anyscene",
            ids=make_ids("edith"),
        )
        self.assertIn("realm/s/grace/+/+/+/+", claims["subs"])
        for topic in claims["publ"]:
            self.assertFalse(
                topic.startswith("realm/s/grace/+/o/"),
                f"namespace viewer must not get object write: {topic}",
            )

    def test_grants_for_other_scenes_are_scoped_out_of_a_scene_token(self):
        """Asking for carol/shared must not also hand over grants on grace/*."""
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="carol/shared",
            ids=make_ids("edith"),
        )
        for topic in claims["publ"] + claims["subs"]:
            with self.subTest(topic=topic):
                self.assertNotIn("/grace/", topic)
                self.assertNotIn("/frank/", topic)

    def test_general_token_includes_every_grant(self):
        """No scene requested: all grants are handed out at once."""
        claims = self.claims(
            user=self.edith, username="edith", realm=REALM, ids=make_ids("edith")
        )
        joined = "\n".join(claims["publ"] + claims["subs"])
        for namespace in ("edith", "carol", "frank", "grace", "public"):
            with self.subTest(namespace=namespace):
                self.assertIn(f"realm/s/{namespace}/", joined)


class GeneralContextTokenTests(ArenaTokenTestCase):
    def test_anonymous_general_token_reads_public_namespace_only(self):
        uid = "anonymous-mike_0000000001"
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ids=make_ids("anonymous-mike"),
        )
        self.assertEqual(claims["publ"], ["$NETWORK/latency"])
        self.assertEqual(
            claims["subs"],
            [
                "$NETWORK",
                "realm/s/public/+/+/+/+",
                f"realm/s/public/+/+/+/+/{uid}/#",
            ],
        )

    def test_authenticated_general_token_has_no_device_grants(self):
        claims = self.claims(user=self.bob, username="bob", realm=REALM, ids=make_ids("bob"))
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                "realm/s/bob/+/o/bob_0000000001_web/#",
                "realm/s/bob/+/p/+/#",
            ],
        )
        self.assertEqual(
            claims["subs"],
            [
                "$NETWORK",
                "realm/s/bob/+/+/+/+",
                "realm/s/bob/+/+/+/+/bob_0000000001/#",
                "realm/s/public/+/+/+/+",
                "realm/s/public/+/+/+/+/bob_0000000001/#",
            ],
        )


class DeviceTokenTests(ArenaTokenTestCase):
    def test_device_owner_gets_device_subtree_only(self):
        claims = self.claims(user=self.bob, username="bob", realm=REALM, ns_device="bob/dev1")
        self.assertEqual(claims["publ"], ["$NETWORK/latency", "realm/d/bob/dev1/#"])
        self.assertEqual(claims["subs"], ["realm/d/bob/dev1/#"])

    def test_device_token_grants_no_scene_topics(self):
        claims = self.claims(user=self.bob, username="bob", realm=REALM, ns_device="bob/dev1")
        for topic in claims["publ"] + claims["subs"]:
            self.assertNotIn("/s/", topic)

    def test_staff_device_token_is_still_scoped_to_that_device(self):
        claims = self.claims(user=self.staff, username="root", realm=REALM, ns_device="bob/dev1")
        self.assertEqual(claims["publ"], ["$NETWORK/latency", "realm/d/bob/dev1/#"])
        self.assertEqual(claims["subs"], ["realm/d/bob/dev1/#"])

    def test_anonymous_device_token_grants_nothing(self):
        claims = self.claims(
            user=self.anon, username="anonymous-mike", realm=REALM, ns_device="bob/dev1"
        )
        self.assertEqual(claims["publ"], ["$NETWORK/latency"])
        self.assertNotIn("subs", claims)


class ApiV1TokenTests(ArenaTokenTestCase):
    """API v1 uses a different, flatter topic layout (deprecated but still issued)."""

    def test_anonymous_scene_topics(self):
        uid = "anonymous-mike_0000000001"
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("anonymous-mike", camid=True),
            version="v1",
        )
        # the chat handle is the userid plus its base64 encoding
        handle = f"{uid}YW5vbnltb3VzLW1pa2VfMDAwMDAwMDAwMQ=="
        self.assertEqual(
            claims["publ"],
            [
                "$NETWORK/latency",
                f"realm/c/carol/o/{handle}",
                f"realm/c/carol/p/+/{handle}",
                "realm/env/carol/plain/#",
                "realm/env/public/#",
                "realm/g/a/#",
                "realm/proc/#",
                f"realm/s/carol/plain/{uid}",
                f"realm/s/carol/plain/{uid}/#",
            ],
        )
        self.assertEqual(
            claims["subs"],
            [
                "realm/c/carol/o/#",
                f"realm/c/carol/p/{uid}/#",
                "realm/g/a/#",
                "realm/proc/#",
                "realm/s/carol/plain/#",
                "realm/s/public/#",
            ],
        )

    def test_anonymous_users_disabled_keeps_public_namespace_only(self):
        claims = self.claims(
            user=self.anon,
            username="anonymous-mike",
            realm=REALM,
            ns_scene="carol/noanon",
            ids=make_ids("anonymous-mike"),
            version="v1",
        )
        self.assertEqual(claims["publ"], ["$NETWORK/latency", "realm/env/public/#"])
        self.assertEqual(claims["subs"], ["realm/s/public/#"])

    def test_owner_scene_topics(self):
        claims = self.claims(
            user=self.bob,
            username="bob",
            realm=REALM,
            ns_scene="bob/scene1",
            ids=make_ids("bob"),
            version="v1",
        )
        self.assertIn("realm/s/bob/#", claims["publ"])
        self.assertIn("realm/env/bob/#", claims["publ"])
        self.assertIn("realm/d/bob/#", claims["publ"])
        self.assertIn("realm/s/bob/#", claims["subs"])
        self.assertNotIn("realm/s/#", claims["publ"])

    def test_staff_scene_topics_include_vio_experiments(self):
        claims = self.claims(
            user=self.staff,
            username="root",
            realm=REALM,
            ns_scene="carol/plain",
            ids=make_ids("root"),
            version="v1",
        )
        self.assertIn("realm/s/#", claims["publ"])
        self.assertIn("realm/env/#", claims["publ"])
        self.assertIn("realm/d/#", claims["publ"])
        self.assertIn("realm/vio/carol/plain/#", claims["publ"])
        self.assertIn("realm/s/#", claims["subs"])

    def test_scene_editor_grant_adds_scene_and_env_topics(self):
        claims = self.claims(
            user=self.edith,
            username="edith",
            realm=REALM,
            ns_scene="carol/shared",
            ids=make_ids("edith"),
            version="v1",
        )
        self.assertIn("realm/s/carol/shared/#", claims["publ"])
        self.assertIn("realm/env/carol/shared/#", claims["publ"])
        self.assertIn("realm/s/carol/shared/#", claims["subs"])
